# Generated by Django 5.0.6 on 2024-06-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emai',
            new_name='email',
        ),
    ]
