# Generated by Django 5.0.7 on 2024-07-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_multimagemodel_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultImgText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='This is to test Multi-image API', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='multimagemodel',
            name='person',
        ),
        migrations.AddField(
            model_name='multimagemodel',
            name='imgtext',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imgtext', to='home.multimgtext'),
        ),
    ]
