# Generated by Django 5.0.7 on 2024-07-16 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_myimage_alter_multimagemodel_imgtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='myImg/')),
            ],
        ),
        migrations.RemoveField(
            model_name='multimagemodel',
            name='imgtext',
        ),
        migrations.DeleteModel(
            name='Test_Images',
        ),
        migrations.RemoveField(
            model_name='myimage',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='my_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.myimage'),
        ),
        migrations.DeleteModel(
            name='MultImageModel',
        ),
        migrations.DeleteModel(
            name='MultImgText',
        ),
    ]
