# Generated by Django 5.0.7 on 2024-07-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_image_my_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
