# Generated by Django 5.0.7 on 2024-07-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_titlevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TitleValue',
        ),
    ]
