# Generated by Django 5.0.7 on 2024-07-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_multimagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimagemodel',
            old_name='tiltle',
            new_name='title',
        ),
    ]
