# Generated by Django 5.0.7 on 2024-07-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_tiltle_multimagemodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimagemodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='test_images',
            name='person',
        ),
        migrations.AddField(
            model_name='multimagemodel',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.person'),
        ),
    ]
