# Generated by Django 5.0.7 on 2024-07-16 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_multimgtext_remove_multimagemodel_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='myImg/')),
            ],
        ),
        migrations.AlterField(
            model_name='multimagemodel',
            name='imgtext',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.multimgtext'),
        ),
    ]
