# Generated by Django 5.0.7 on 2024-07-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_image_remove_multimagemodel_imgtext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='my_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='home.myimage'),
        ),
    ]
